jupyterhub:
  proxy:
    service:
      type: NodePort

  singleuser:
    storage:
      capacity: 1Gi
    memory:
      limit: 4G
      guarantee: 1G
    cpu:
      limit: 2
      guarantee: 0.1
  #   extraEnv:
  #     DEFAULT_LANDING: /
      # DEFAULT_LANDING: /files/landing_pages/_site/Content/index.html

  auth:
    type: github
    admin:
      access: true

  # Disable the image pre-puller since it reliably fails on the kops setup
  # clusters that I tried.
  prePuller:
    hook:
      enabled: false
